### PR TITLE
Added error message if date entered in ONS_geolist is in the wrong format

### PR DESCRIPTION
**Pull request by phil-hall-moj**
Added the same date format error handling to ONS_geolist() as was added to geocheck()

Resolves issue #7

### CODE REVIEW

**Comment by BrydenFrancesca** [comment]
Function produces error as expected with incorrect value, but doesn't filter on correct value. Not sure if related to this change or not, have raised as a separate issue #9 and can investigate next week.

**Comment by BrydenFrancesca** [comment]
Function produces error with most incorrect date values, but fails with DD-MMM-YYYY format. E.g. "12-Dec-2014" filters for "12-Dec-20" rather than producing an error.

**Comment by BrydenFrancesca** [comment]
I've added a `nchar(date) > 9` condition to the error message in both functions to get around the previous issue, so a YYYY format date will also return the same error rather than silently filtering incorrectly.

**Review by ashtaylor42 — COMMENTED** [review]
looks good

**Review by BrydenFrancesca — APPROVED** [review]

**Pull request merged**
